services:
  aspire-app:
    image: aspire-app   # <-- replace with your Aspire app image
    container_name: aspire-app
    environment:
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
    ports:
      - "8080:8080" 
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
    command: ["run", "/etc/alloy/config.alloy"]
    depends_on:
      - aspire-app
      - mimir
      - loki
      - tempo
    networks:
      - observability

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    volumes:
      - ./mimir.yaml:/etc/mimir/mimir.yaml:ro
    command: ["-config.file=/etc/mimir/mimir.yaml"]
    ports:
      - "9009:9009"
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml:ro
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml
    ports:
      - "3200:3200"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - mimir
      - tempo
      - loki
    networks:
      - observability
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning

networks:
  observability:
    driver: bridge

volumes:
  grafana-storage:
  minio-data:
