version: '3.9'

services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire-dashboard
    ports:
      - "18888:18888" # Dashboard UI
      - "4317:18889"   # OTLP ingestion
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"

  myapp:
    build: .
    container_name: aspire-test
    ports:
      - "8080:80"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889" # OTLP for telemetry
    depends_on:
      - aspire-dashboard
