# values override for opentelemetry-collector chart
mode: deployment

presets:
  logsCollection:
    enabled: false

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.99.0

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  processors:
    batch: {}
  exporters:
    otlp/jaeger:
      endpoint: jaeger-collector.observability.svc.cluster.local:4317
      tls:
        insecure: true
    loki:
      endpoint: http://loki-gateway.loki-testing.svc.cluster.local/loki/api/v1/push
      tls:
        insecure: true
      headers:
        X-Scope-OrgID: tenant1
    logging:
      verbosity: basic
    prometheus:
      endpoint: 0.0.0.0:9464
      namespace: app
      const_labels:
        source: otelcol
  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8889
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/jaeger]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [loki, logging]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus, logging]
resources: {}
