FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
RUN apt-get update
RUN apt-get install -y wget
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_URLS=http://*:80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./aspire-testing.csproj src/
RUN dotnet restore "src/aspire-testing.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "aspire-testing.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "aspire-testing.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "aspire-testing.dll"]