apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aspire-apps
  namespace: observability
  labels:
    release: my-kube-prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      metrics-scrape: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
